# -*- coding: utf-8 -*-
"""x.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iNqNRFSp6zTDxv6stk_aDSPqyjOm0PTN
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_excel('/content/messy_sales_dataset.xlsx')

df.isnull().sum()

df.duplicated().sum()

df["Date"] = pd.to_datetime(
    df["Date"],
    format="mixed",
    dayfirst=True,
    errors="coerce"
)

df["Date"].isnull().sum()

df = df.drop_duplicates().copy()

df.duplicated().sum()

df.isnull().sum()

df["Region"] = df["Region"].str.strip().str.title()

df.isnull().sum()

df["Product"] = df["Product"].str.strip().str.title()

df["Product"].unique()

df["Category"] = df["Category"].str.strip().str.title()

df["Category"] = df["Category"].replace({
    "Electroncs": "Electronics",
    "Electrnics": "Electronics",
    "electronics": "Electronics"
})

df["Category"].unique()

print("Units_Sold:", (df["Units_Sold"] < 0).sum())
print("Unit_Price:", (df["Unit_Price"] < 0).sum())
print("Marketing_Spend:", (df["Marketing_Spend"] < 0).sum())

df.loc[df["Units_Sold"] < 0, "Units_Sold"] = np.nan

df.loc[df["Unit_Price"] < 0, "Unit_Price"] = np.nan

df.loc[df["Marketing_Spend"] < 0, "Marketing_Spend"] = np.nan

df["Discount_%"] = df["Discount_%"].fillna(df["Discount_%"].median())

df["Customer_Rating"] = df["Customer_Rating"].fillna(df["Customer_Rating"].median())

df["Units_Sold"] = df["Units_Sold"].fillna(df["Units_Sold"].median())

df["Unit_Price"] = df["Unit_Price"].fillna(df["Unit_Price"].median())

df["Marketing_Spend"] = df["Marketing_Spend"].fillna(df["Marketing_Spend"].median())

df["Revenue"] = (
    df["Units_Sold"] *
    df["Unit_Price"] *
    (1 - df["Discount_%"] / 100)
)

df.isnull().sum()

df.to_excel("cleaned_sales_data.xlsx", index=False)

from google.colab import files

files.download("cleaned_sales_data.xlsx")

# EXPLORATORY DATA ANALYSIS (EDA)

df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Day"] = df["Date"].dt.day
df["Quarter"] = df["Date"].dt.quarter
df["Day_of_Week"] = df["Date"].dt.day_name()

print("Total Revenue:", df["Revenue"].sum())

print("Average Revenue:", df["Revenue"].mean())

region_sales = df.groupby("Region")["Revenue"].sum()

print(region_sales)

plt.figure(figsize=(8,5))

region_sales.plot(kind="bar")

plt.title("Revenue by Region")
plt.xlabel("Region")
plt.ylabel("Revenue")

plt.show()

plt.figure(figsize=(8,5))

region_sales.plot(kind="bar")

plt.title("Revenue by Region")
plt.xlabel("Region")
plt.ylabel("Revenue")

plt.savefig("region_sales.png")

plt.show()

monthly_sales = df.groupby("Month")["Revenue"].sum()

print(monthly_sales)

plt.figure(figsize=(10,5))

monthly_sales.plot(kind="line", marker="o")

plt.title("Monthly Revenue")
plt.xlabel("Month")
plt.ylabel("Revenue")
plt.grid(True)

plt.show()

product_sales = df.groupby("Product")["Revenue"].sum()

print(product_sales)

top5 = product_sales.sort_values(ascending=False).head(5)

print(top5)

plt.figure(figsize=(10,5))

top5.plot(kind="bar")

plt.title("Top 5 Products")
plt.xlabel("Product")
plt.ylabel("Revenue")

plt.show()

plt.figure(figsize=(8,5))

plt.hist(df["Customer_Rating"], bins=10)

plt.title("Customer Rating Distribution")
plt.xlabel("Rating")
plt.ylabel("Count")

plt.show()

plt.figure(figsize=(8,5))

plt.hist(df["Revenue"], bins=20)

plt.title("Revenue Distribution")
plt.xlabel("Revenue")
plt.ylabel("Frequency")

plt.show()

df.to_excel("cleaned_sales_data.xlsx", index=False)

# Machine Learning (Linear Regression)

features = [
    "Units_Sold",
    "Unit_Price",
    "Discount_%",
    "Marketing_Spend",
    "Customer_Rating",
    "Month",
    "Quarter",
    "Year"
]

X = df[features]
y = df["Revenue"]

# Split the Dataset

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Data:", X_train.shape)
print("Testing Data :", X_test.shape)

from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import numpy as np

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error :", mae)
print("Mean Squared Error  :", mse)
print("Root Mean Squared Error :", rmse)
print("R² Score :", r2)

results = pd.DataFrame({
    "Actual Revenue": y_test,
    "Predicted Revenue": y_pred
})

results.head(10)

plt.figure(figsize=(8,6))

plt.scatter(y_test, y_pred)

plt.title("Actual vs Predicted Revenue")
plt.xlabel("Actual Revenue")
plt.ylabel("Predicted Revenue")

plt.show()

import joblib

joblib.dump(model, "linear_regression_model.pkl")

results.to_excel("prediction_results.xlsx", index=False)

coefficients = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_
})

coefficients.sort_values(by="Coefficient", ascending=False)

